<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_serializer.handler_registry' shared service.

include_once $this->targetDirs[3].'/vendor/jms/serializer/src/JMS/Serializer/Handler/HandlerRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Serializer/JMSHandlerRegistry.php';

return $this->services['jms_serializer.handler_registry'] = new \FOS\RestBundle\Serializer\JMSHandlerRegistry(($this->privates['fos_rest.serializer.jms_handler_registry.inner'] ?? $this->load('getFosRest_Serializer_JmsHandlerRegistry_InnerService.php')));
