<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUed9L3x\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUed9L3x/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUed9L3x.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUed9L3x\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUed9L3x\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ued9L3x',
    'container.build_id' => '72c46fb6',
    'container.build_time' => 1523263927,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUed9L3x');
